apps/accounts/urls.py
from django.conf import settings
from django.urls import path, include

app_name = "accounts"


from accounts.views import ProfileJSONView


urlpatterns = [path("profile/", ProfileJSONView, name="profile_json")]

apps/core/urls.py
from django.conf import settings
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "core"


favicon_view = RedirectView.as_view(
    url=settings.STATIC_URL + "core/img/favicon.ico", permanent=True
)

urlpatterns = [
    path("", TemplateView.as_view(template_name="core/index.html"), name="index"),
    path("favicon.ico", favicon_view, name="favicon"),
    path("i18n/", include("django.conf.urls.i18n")),
]

provider/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
import oauth2_provider.views as oauth2_views

# OAuth2 provider endpoints
oauth2_endpoint_views = [
    url(r"^authorize/$", oauth2_views.AuthorizationView.as_view(), name="authorize"),
    url(r"^token/$", oauth2_views.TokenView.as_view(), name="token"),
    url(
        r"^revoke-token/$", oauth2_views.RevokeTokenView.as_view(), name="revoke-token"
    ),
]


urlpatterns = [
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    url(r"^accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    url(r"^o/", include(oauth2_endpoint_views)),
]

apps/accounts/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    # automatic
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        if self.first_name and self.last_name:
            return "{} {}".format(self.first_name, self.last_name)
        else:
            return self.username

apps/core/models.py
from django.db import models

# Create your models here.

apps/accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.utils.translation import gettext, gettext_lazy as _


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label=_("first name").capitalize())
    last_name = forms.CharField(max_length=150, label=_("last name").capitalize())

    def signup(self, request, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user

apps/accounts/views.py
import json
from django.http import HttpResponse
from oauth2_provider.decorators import protected_resource


@protected_resource(scopes=["read"])
def ProfileJSONView(request):
    return HttpResponse(
        json.dumps(
            {
                "id": str(request.resource_owner.id),
                "username": request.resource_owner.username,
                "email": request.resource_owner.email,
                "first_name": request.resource_owner.first_name,
                "last_name": request.resource_owner.last_name,
            }
        ),
        content_type="application/json",
    )

apps/core/views.py
from django.shortcuts import render

# Create your views here.

apps/core/templates/core/_footer.html
{% load i18n %}
<footer class="page-footer font-small bg-secondary text-white pt-4 footer mt-auto" role="contentinfo">
    <div class="container-fluid text-center text-md-left">
        <div class="row text-center">
            <div class="col-md-4 mt-md-0 mt-3">
            </div>
            <div class="col-md-4 mt-md-0 mt-3">
                <h5 class="text-uppercase"><i class="fas fa-tools"></i> {{ request.site.name }}</h5>
                <p>{{ request.site.url }}</p>
            </div>
            <div class="col-md-4 mt-md-0 mt-3">
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3 bg-dark text-white">
        &copy; <a href="https://github.com/myworkshopproject" class="text-white">MyWorkshopProject</a> {% now "Y" %}
    </div>
</footer>

apps/core/templates/core/_header.html
<header role="banner">
</header>

apps/core/templates/core/_lang_select_button.html
{% load i18n %}
<div class="dropdown">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_language_info for LANGUAGE_CODE as lang %}
        {{ lang.name_local }} ({{ lang.code }})
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}

        {% for language in languages %}
        {% if language.code != LANGUAGE_CODE %}
        <form action="{% url 'set_language' %}" method="post" class="form-inline">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <input name="language" type="hidden" value="{{ language.code }}">
            <input type="submit" class="dropdown-item" value="{{ language.name_local }} ({{ language.code }})">
        </form>
        {% endif %}
        {% endfor %}
    </div>
</div>

apps/core/templates/core/_nav.html
{% load i18n %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark" role="navigation">
    <a class="navbar-brand" href="{% url 'core:index' %}"><i class="fas fa-tools"></i> {{ request.site.name }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">

        </ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_language_info for LANGUAGE_CODE as lang %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ lang.name_local }} ({{ lang.code }})
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    {% for language in languages %}
                    {% if language.code != LANGUAGE_CODE %}
                    <form action="{% url 'core:set_language' %}" method="post" class="form-inline">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <input name="language" type="hidden" value="{{ language.code }}">
                        <input type="submit" class="dropdown-item" value="{{ language.name_local }} ({{ language.code }})">
                    </form>
                    {% endif %}
                    {% endfor %}
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.first_name and user.last_name %}
                    {{ user.first_name }} {{ user.last_name }}
                    {% else %}
                    {{ user.get_username }}
                    {% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}
                    <a class="dropdown-item" href="#">{% trans "Account" %}</a>
                    <a class="dropdown-item" href="{% url 'account_email' %}">{% trans "E-mail Addresses" %}</a>
                    <a class="dropdown-item" href="{% url 'socialaccount_connections' %}">{% trans "Account Connections" %}</a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">{% trans 'Change my password' %}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans 'Log out' %}</a>
                </div>
            </li>
            {% else %}
            <form class="form-inline ml-auto">
                <a class="btn btn-outline-secondary" href="{% url 'account_login' %}">{% trans 'Log in' %}</a>
                <a class="btn btn-primary ml-2" href="{% url 'account_signup' %}">{% trans 'Signup' %}</a>
            </form>
            {% endif %}
        </ul>
    </div>
</nav>

apps/core/templates/core/_pagination_bar.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
        <li class="page-item{% if page_obj.number == i %} active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i }} <span class="sr-only">(current)</span></a></li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

apps/core/templates/core/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" dir="ltr" class="h-100">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootswatch CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/united/bootstrap.min.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}">

    <!-- Font Awesome's Free CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />

    <title>{{ request.site.name }} | {% block head_title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% url 'core:favicon' %}" />

    {% block extra_head %}
    {% endblock %}
</head>

<body class="d-flex flex-column h-100 {% block body_class %}{% endblock %}">
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block extra_body %}
    {% endblock %}
</body>

</html>

apps/core/templates/core/base_dark.html
{% extends "core/base.html" %}

{% load i18n %}

{% block body_class %}bg-dark{% endblock %}

{% block body %}
<main role="main" class="flex-shrink-0">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto align-middle">
                {% if messages %}
                {% for message in messages %}
                {% include 'core/utils/message.html' %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto align-middle">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

apps/core/templates/core/index.html
{% extends "core/page.html" %}
{% load i18n %}

{% block head_title %}{% trans 'Home' %}{% endblock %}

{% block jumbotron_title %}<i class="fas fa-tools"></i> {{ request.site.name }}{% endblock %}
{% block jumbotron_lead %}{{ request.site.domain }}{% endblock %}

{% block content %}
<h1>{% trans 'Home' %}</h1>
{% endblock %}

apps/core/templates/core/page.html
{% extends "core/base.html" %}
{% load i18n %}

{% block head_title %}{% trans 'Home' %}{% endblock %}

{% block body %}
{% include 'core/_header.html' %}
{% include 'core/_nav.html' %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{% block jumbotron_title %}{% endblock %}</h1>
        <p class="lead">{% block jumbotron_lead %}{% endblock %}</p>
        {% block jumbotron_footer %}{% endblock %}
    </div>
</div>
<main role="main" class="flex-shrink-0">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                {% for message in messages %}
                {% include 'core/utils/message.html' %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
                {% if is_paginated %}
                {% include 'core/_pagination_bar.html' %}
                {% endif %}
            </div>
        </div>
    </div>
</main>
{% include 'core/_footer.html' %}
{% endblock %}

apps/core/templates/core/utils/message.html
{% load i18n %}

{% if message.level_tag == "success" %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <i class="fas fa-check-circle"></i>
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% elif message.level_tag == "info" %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <i class="fas fa-info-circle"></i>
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% elif message.level_tag == "warning" %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <i class="fas fa-exclamation-triangle"></i>
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% elif message.level_tag == "error" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <i class="fas fa-exclamation-circle"></i>
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% else %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endif %}

templates/oauth2_provider/application_confirm_delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Are you sure to delete the application" %} {{ application.name }}?</h3>
        <form method="post" action="{% url 'oauth2_provider:delete' application.pk %}">
            {% csrf_token %}

            <div class="control-group">
                <div class="controls">
                    <a class="btn btn-large" href="{% url "oauth2_provider:list" %}">{% trans "Cancel" %}</a>
                    <input type="submit" class="btn btn-large btn-danger" name="allow" value="{% trans "Delete" %}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

templates/oauth2_provider/application_detail.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{{ application.name }}</h3>

        <ul class="unstyled">
            <li>
                <p><b>{% trans "Client id" %}</b></p>
                <input class="input-block-level" type="text" value="{{ application.client_id }}" readonly>
            </li>

            <li>
                <p><b>{% trans "Client secret" %}</b></p>
                <input class="input-block-level" type="text" value="{{ application.client_secret }}" readonly>
            </li>

            <li>
                <p><b>{% trans "Client type" %}</b></p>
                <p>{{ application.client_type }}</p>
            </li>

            <li>
                <p><b>{% trans "Authorization Grant Type" %}</b></p>
                <p>{{ application.authorization_grant_type }}</p>
            </li>

            <li>
                <p><b>{% trans "Redirect Uris" %}</b></p>
                <textarea class="input-block-level" readonly>{{ application.redirect_uris }}</textarea>
            </li>
        </ul>

        <div class="btn-toolbar">
            <a class="btn" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
            <a class="btn btn-primary" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
        </div>
    </div>
{% endblock content %}

templates/oauth2_provider/application_form.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <form class="form-horizontal" method="post" action="{% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
            <h3 class="block-center-heading">
                {% block app-form-title %}
                    {% trans "Edit application" %} {{ application.name }}
                {% endblock app-form-title %}
            </h3>
            {% csrf_token %}

            {% for field in form %}
                <div class="control-group {% if field.errors %}error{% endif %}">
                    <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="controls">
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-inline">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div class="control-group {% if form.non_field_errors %}error{% endif %}">
                {% for error in form.non_field_errors %}
                    <span class="help-inline">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="control-group">
                <div class="controls">
                    <a class="btn" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                        {% trans "Go Back" %}
                    </a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/oauth2_provider/application_list.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Your applications" %}</h3>
        {% if applications %}
            <ul>
                {% for application in applications %}
                    <li><a href="{{ application.get_absolute_url }}">{{ application.name }}</a></li>
                {% endfor %}
            </ul>

            <a class="btn btn-success" href="{% url "oauth2_provider:register" %}">New Application</a>
        {% else %}
            <p>{% trans "No applications defined" %}. <a href="{% url 'oauth2_provider:register' %}">{% trans "Click here" %}</a> {% trans "if you want to register a new one" %}</p>
        {% endif %}
    </div>
{% endblock content %}

templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block app-form-title %}{% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth2_provider:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

templates/oauth2_provider/authorize.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Authorize" %} {{ application.name }}?{% endblock %}

{% block card_header %}{% trans "Authorize" %} {{ application.name }}?{% endblock %}

{% block card_body %}
<div class="card-body">
    {% if not error %}
    <form id="authorizationForm" method="post">
        {% csrf_token %}

        {% for field in form %}
        {% if field.is_hidden %}
        {{ field }}
        {% endif %}
        {% endfor %}

        <p class="card-text">{% trans "Application requires following permissions" %}</p>
        <ul>
            {% for scope in scopes_descriptions %}
            <li>{{ scope }}</li>
            {% endfor %}
        </ul>

        {{ form.errors }}
        {{ form.non_field_errors }}

        <input type="submit" class="btn btn-secondary" value="Cancel" />
        <input type="submit" class="btn btn-primary" name="allow" value="Authorize" />
    </form>

    {% else %}
    <h4>Error: {{ error.error }}</h4>
    <p class="card-text">{{ error.description }}</p>
    {% endif %}
</div>
{% endblock %}

templates/oauth2_provider/authorized-token-delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Authorize" %} {{ application.name }}?{% endblock %}

{% block card_header %}{% trans "Authorize" %} {{ application.name }}?{% endblock %}

{% block card_body %}
<div class="card-body">
    <form action="" method="post">{% csrf_token %}
        <p class="card-text">{% trans "Are you sure you want to delete this token?" %}</p>
        <input class="btn btn-primary" type="submit" value="{% trans " Delete" %}" />
    </form>
</div>
{% endblock %}

templates/oauth2_provider/authorized-tokens.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Tokens" %}{% endblock %}

{% block card_header %}{% trans "Tokens" %}{% endblock %}

{% block card_body %}
<div class="card-body">
    <ul>
        {% for authorized_token in authorized_tokens %}
        <li>
            {{ authorized_token.application }}
            (<a href="{% url 'oauth2_provider:authorized-token-delete' authorized_token.pk %}">revoke</a>)
        </li>
        <ul>
            {% for scope_name, scope_description in authorized_token.scopes.items %}
            <li>{{ scope_name }}: {{ scope_description }}</li>
            {% endfor %}
        </ul>
        {% empty %}
        <li>{% trans "There are no authorized tokens yet." %}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/oauth2_provider/base.html
{% extends "core/base_dark.html" %}

{% load i18n %}

{% block content %}
<div class="card">
    <h4 class="card-header">
        {% block card_header %}card header{% endblock %}
    </h4>
    {% block card_body %}{% endblock %}
    <div class="card-footer text-muted">
        {% block card_footer %}<a class="text-muted" href="{% url 'core:index' %}">{% trans 'Home' %}</a>{% endblock %}
    </div>
</div>
{% endblock %}